// Code generated by servoc (gohttp plugin). DO NOT EDIT.
package example

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/labstack/echo/v4"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
)

/////////////////////////////
// EchoService HTTP server //
/////////////////////////////

type EchoServiceHttpEndpoints interface {
	Echo(echo.Context, *EchoRequest) (*EchoResponse, error)
}

func NewEchoServiceHttpServer(svc EchoServiceHttpEndpoints) *echo.Echo {
	srv := echo.New()
	RegisterEchoServiceRPCs(svc, srv)
	return srv
}

func RegisterEchoServiceRPCs(svc EchoServiceHttpEndpoints, srv *echo.Echo) {
	RegisterEchoServiceRPCsGroup(svc, srv.Group("/"))
}

func RegisterEchoServiceRPCsGroup(svc EchoServiceHttpEndpoints, srv *echo.Group) {
	compat := &echoServiceHttpAdapter{svc}
	srv.POST("echo-service/echo", compat.Echo)
}

type echoServiceHttpAdapter struct {
	svc EchoServiceHttpEndpoints
}

// HTTP compatibility wrapper for EchoService.echo.
func (s *echoServiceHttpAdapter) Echo(c echo.Context) error {
	req := new(EchoRequest)
	if err := c.Bind(req); err != nil {
		return err
	}
	res, err := s.svc.Echo(c, req)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err)
	}
	return c.JSON(http.StatusOK, res)
}

/////////////////////////////
// EchoService HTTP client //
/////////////////////////////

type EchoServiceHttpClient interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func NewEchoServiceHttpClient(baseUrl string) EchoServiceHttpClient {
	return NewDelegatingEchoServiceHttpClient(baseUrl, new(http.Client))
}

func NewDelegatingEchoServiceHttpClient(baseUrl string, delegate *http.Client) EchoServiceHttpClient {
	return &echoServiceHttpClient{baseUrl, delegate}
}

var _ EchoServiceHttpClient = new(echoServiceHttpClient)

type echoServiceHttpClient struct {
	baseUrl  string
	delegate *http.Client
}

func (client *echoServiceHttpClient) Echo(ctx context.Context, request *EchoRequest) (*EchoResponse, error) {
	u, err := url.JoinPath(client.baseUrl, "/echo-service/echo")
	if err != nil {
		return nil, err
	}

	body := new(bytes.Buffer)
	if err := json.NewEncoder(body).Encode(request); err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")

	res, err := client.delegate.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		return nil, errors.New("unexpected status code " + strconv.Itoa(res.StatusCode))
	}

	response := new(EchoResponse)
	return response, json.NewDecoder(res.Body).Decode(response)
}

//////////////////////////////////
// EchoService test HTTP client //
//////////////////////////////////

func NewEchoServiceTestHttpClient(svc EchoServiceHttpEndpoints) EchoServiceHttpClient {
	return &echoServiceHttpTestClient{svc}
}

var _ EchoServiceHttpClient = new(echoServiceHttpTestClient)

type echoServiceHttpTestClient struct {
	service EchoServiceHttpEndpoints
}

func (client *echoServiceHttpTestClient) Echo(_ context.Context, request *EchoRequest) (*EchoResponse, error) {
	body := new(bytes.Buffer)
	if err := json.NewEncoder(body).Encode(request); err != nil {
		return nil, err
	}
	req := httptest.NewRequest(http.MethodPost, "/echo-service/echo", body)
	req.Header.Set("Content-Type", "application/json")
	res := httptest.NewRecorder()

	ctx := NewEchoServiceHttpServer(client.service).NewContext(req, res)
	if err := (&echoServiceHttpAdapter{client.service}).Echo(ctx); err != nil {
		return nil, err
	} else if res.Code != http.StatusOK {
		return nil, errors.New("unexpected status code " + strconv.Itoa(res.Code))
	}

	response := new(EchoResponse)
	return response, json.NewDecoder(res.Body).Decode(response)
}

//////////////////////////////////
// TelemetryService HTTP server //
//////////////////////////////////

type TelemetryServiceHttpEndpoints interface {
	Publish(echo.Context, *Telemetry) error
}

func NewTelemetryServiceHttpServer(svc TelemetryServiceHttpEndpoints) *echo.Echo {
	srv := echo.New()
	RegisterTelemetryServiceRPCs(svc, srv)
	return srv
}

func RegisterTelemetryServiceRPCs(svc TelemetryServiceHttpEndpoints, srv *echo.Echo) {
	RegisterTelemetryServiceRPCsGroup(svc, srv.Group("/"))
}

func RegisterTelemetryServiceRPCsGroup(svc TelemetryServiceHttpEndpoints, srv *echo.Group) {
	compat := &telemetryServiceHttpAdapter{svc}
	srv.POST("telemetry-service/publish", compat.Publish)
}

type telemetryServiceHttpAdapter struct {
	svc TelemetryServiceHttpEndpoints
}

// HTTP compatibility wrapper for TelemetryService.publish.
func (s *telemetryServiceHttpAdapter) Publish(c echo.Context) error {
	req := new(Telemetry)
	if err := c.Bind(req); err != nil {
		return err
	}
	err := s.svc.Publish(c, req)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err)
	}
	return c.NoContent(http.StatusNoContent)
}

//////////////////////////////////
// TelemetryService HTTP client //
//////////////////////////////////

type TelemetryServiceHttpClient interface {
	Publish(context.Context, *Telemetry) error
}

func NewTelemetryServiceHttpClient(baseUrl string) TelemetryServiceHttpClient {
	return NewDelegatingTelemetryServiceHttpClient(baseUrl, new(http.Client))
}

func NewDelegatingTelemetryServiceHttpClient(baseUrl string, delegate *http.Client) TelemetryServiceHttpClient {
	return &telemetryServiceHttpClient{baseUrl, delegate}
}

var _ TelemetryServiceHttpClient = new(telemetryServiceHttpClient)

type telemetryServiceHttpClient struct {
	baseUrl  string
	delegate *http.Client
}

func (client *telemetryServiceHttpClient) Publish(ctx context.Context, request *Telemetry) error {
	u, err := url.JoinPath(client.baseUrl, "/telemetry-service/publish")
	if err != nil {
		return err
	}

	body := new(bytes.Buffer)
	if err := json.NewEncoder(body).Encode(request); err != nil {
		return err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	res, err := client.delegate.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusNoContent {
		return errors.New("unexpected status code " + strconv.Itoa(res.StatusCode))
	}
	return nil
}

///////////////////////////////////////
// TelemetryService test HTTP client //
///////////////////////////////////////

func NewTelemetryServiceTestHttpClient(svc TelemetryServiceHttpEndpoints) TelemetryServiceHttpClient {
	return &telemetryServiceHttpTestClient{svc}
}

var _ TelemetryServiceHttpClient = new(telemetryServiceHttpTestClient)

type telemetryServiceHttpTestClient struct {
	service TelemetryServiceHttpEndpoints
}

func (client *telemetryServiceHttpTestClient) Publish(_ context.Context, request *Telemetry) error {
	body := new(bytes.Buffer)
	if err := json.NewEncoder(body).Encode(request); err != nil {
		return err
	}
	req := httptest.NewRequest(http.MethodPost, "/telemetry-service/publish", body)
	req.Header.Set("Content-Type", "application/json")
	res := httptest.NewRecorder()

	ctx := NewTelemetryServiceHttpServer(client.service).NewContext(req, res)
	if err := (&telemetryServiceHttpAdapter{client.service}).Publish(ctx); err != nil {
		return err
	} else if res.Code != http.StatusNoContent {
		return errors.New("unexpected status code " + strconv.Itoa(res.Code))
	}
	return nil
}
