// Code generated by servoc (gostruct plugin). DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"time"
)

type (
	URN string
	Bit bool
)

type EchoRequest struct {
	Message string `db:"message" json:"message"`
}

type EchoResponse struct {
	Message   string    `db:"message" json:"message"`
	Id        uuid.UUID `db:"id" json:"id"`
	Signature []byte    `db:"signature" json:"signature"`
}

type Metric struct {
	Type   MetricType        `db:"type" json:"type"`
	Name   string            `db:"name" json:"name"`
	Labels map[string]string `db:"labels" json:"labels"`
	Value  float64           `db:"value" json:"value"`
	At     time.Time         `db:"at" json:"at"`
}

type Binary struct {
	Location *URN  `db:"location" json:"location"`
	Bits     []Bit `db:"bits" json:"bits"`
}

type Log struct {
	Labels map[string]string `db:"labels" json:"labels"`
	Value  string            `db:"value" json:"value"`
}

type MetricType string

const (
	MetricType_Counter MetricType = "COUNTER"
	MetricType_Gauge   MetricType = "GAUGE"
)

type Telemetry struct {
	TelemetryType string  `db:"@type" json:"@type"`
	Log           *Log    `db:"log,omitempty" json:"log,omitempty"`
	Metric        *Metric `db:"metric,omitempty" json:"metric,omitempty"`
	Name          *string `db:"name,omitempty" json:"name,omitempty"`
}

func (u *Telemetry) UnmarshalJSON(p []byte) error {
	if u == nil {
		return errors.New("unable to unmarshal into nil Telemetry pointer")
	}

	var discriminator struct {
		Type string `db:"@type" json:"@type"`
	}
	if err := json.Unmarshal(p, &discriminator); err != nil {
		return err
	}

	switch discriminator.Type {
	case "log", "metric", "name":
		return json.Unmarshal(p, u)
	default:
		return fmt.Errorf("unknown Telemetry type \"%s\"", discriminator.Type)
	}

}

func NewTelemetryLog(value Log) *Telemetry {
	return &Telemetry{TelemetryType: "log", Log: &value}
}

func NewTelemetryMetric(value Metric) *Telemetry {
	return &Telemetry{TelemetryType: "metric", Metric: &value}
}

func NewTelemetryName(value string) *Telemetry {
	return &Telemetry{TelemetryType: "name", Name: &value}
}

type EchoService interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

type TelemetryService interface {
	Publish(context.Context, *Telemetry) error
}
