package ipc

import "github.com/egoodhall/servo/pkg/ast"

type GenerateRequest struct {
	// Options that should be applied to all files
	Options []ast.Option
	// AST for all parsed
	Files []ast.File
}

type GenerateResponse struct {
	// Names of files that were generated by the extension
	Files []string
}

type InfoRequest struct {
}

type InfoResponse struct {
	Name    string
	Version string
	Options []Option
}

type Option struct {
	Name        string
	Default     string
	Description string
}
