// generated by Textmapper; DO NOT EDIT

package parsegen

import (
	"fmt"

	"github.com/egoodhall/servo/parser/parsegen/token"
)

var tmNonterminals = [...]string{
	"Comment",
	"WhiteSpace",
	"WhiteSpace$1",
	"OptionName",
	"OptionString",
	"OptionBool",
	"OptionInt",
	"OptionFloat",
	"OptionScalar",
	"OptionSliceElement",
	"OptionSlice",
	"OptionSlice$1",
	"Ws_optlist",
	"OptionMapKey",
	"OptionMapValue",
	"OptionMapEntry",
	"OptionMap",
	"OptionMap$1",
	"OptionValue",
	"Option",
	"TypeRef",
	"FieldName",
	"ScalarType",
	"MapKeyType",
	"MapValueType",
	"MapType",
	"ListElementType",
	"ListType",
	"FieldMod",
	"FieldType",
	"FieldDef",
	"FieldDefList",
	"MessageName",
	"FieldDefList_optlist",
	"Message",
	"UnionMemberName",
	"UnionMemberType",
	"UnionMember",
	"UnionMemberList",
	"UnionName",
	"Union",
	"UnionMemberList_optlist",
	"RpcName",
	"RpcRequest",
	"RpcResponse",
	"Method",
	"MethodList",
	"ServiceName",
	"MethodList_list",
	"Service",
	"EnumName",
	"EnumValue",
	"EnumField",
	"EnumValueList",
	"Enum",
	"EnumValueList_list",
	"AliasName",
	"AliasType",
	"Alias",
	"Definition",
	"DefinitionList",
	"DefinitionList_optlist",
	"ServoFile",
}

func symbolName(sym int32) string {
	if sym == noToken {
		return "<no-token>"
	}
	if sym < int32(token.NumTokens) {
		return token.Type(sym).String()
	}
	if i := int(sym) - int(token.NumTokens); i < len(tmNonterminals) {
		return tmNonterminals[i]
	}
	return fmt.Sprintf("nonterminal(%d)", sym)
}

var tmAction = []int32{
	-3, 6, 1, 0, 5, 211, -27, -71, -89, 4, 3, -1, -1, -1, -1, -1, -1, -1, 204,
	200, 201, 202, 203, 205, -107, 210, 185, -1, 65, -1, 86, -1, 178, -1, 7, -1,
	197, -1, 206, 207, 209, -1, -1, -131, -1, -145, -1, -1, -1, -1, -1, 186, -1,
	-1, -159, 196, -1, -1, 67, -1, -171, 92, -1, -185, -1, -1, -199, 180, -1, -1,
	22, 8, 9, 10, 11, 22, 29, 30, 31, 32, 33, 34, 35, -1, 198, -1, -1, 188, -1,
	190, 194, 195, -1, -1, -1, -1, 39, 71, -1, -211, 66, 67, -1, -1, -1, 72, 90,
	-1, -225, 91, 92, -1, 93, -1, -1, 177, 184, 179, -1, -1, -1, -1, 36, 199,
	193, 187, -1, 192, 70, 61, 62, -1, -1, 64, -1, 69, 89, 82, 83, -1, -1, 85,
	-1, 88, -1, -1, 183, -1, 182, 21, 12, 13, 14, 15, 16, 17, 20, 23, -1, 28,
	191, 37, -1, 38, -1, 40, -239, -251, -263, -1, -1, 68, -1, 73, -1, -1, 87,
	-1, 94, -1, -1, 181, -275, -1, -283, -291, 44, -1, -1, -1, 46, 47, 49, 51,
	60, -1, -1, -1, -1, 81, -1, -1, -1, -1, -1, -1, -1, -1, 22, -1, 24, 25, 22,
	-1, -1, 45, 58, -1, 59, -1, 56, -1, 79, -1, 80, -1, 77, -1, -1, -1, -1, 175,
	-1, -1, -1, -1, -1, -1, 18, -1, 26, 42, -1, 57, 54, -1, 55, 78, 75, -1, 76,
	-1, 155, -1, -1, -1, 95, -1, -1, 174, -1, 165, -1, -1, -1, -1, 135, -1, -1,
	19, 27, 43, 53, 74, -1, -1, -1, 154, -1, 145, -1, -1, 173, -1, -1, -1, -1,
	-1, -1, 164, -1, 115, -1, -1, -1, -1, -1, 134, -1, 125, -1, -1, 153, -1, -1,
	-1, -1, -1, -1, 144, 171, -1, 172, -1, 169, -1, -1, 163, -1, -1, -1, -1, -1,
	-1, 114, -1, 105, -1, -1, 133, -1, -1, -1, -1, -1, -1, 124, 151, -1, 152, -1,
	149, -1, -1, 143, -1, -1, -1, 170, 167, -1, 168, 161, -1, 162, -1, 159, -1,
	-1, 113, -1, -1, -1, -1, -1, -1, 104, 131, -1, 132, -1, 129, -1, -1, 123, -1,
	-1, -1, 150, 147, -1, 148, 141, -1, 142, -1, 139, -1, 166, 160, 157, -1, 158,
	111, -1, 112, -1, 109, -1, -1, 103, -1, -1, -1, 130, 127, -1, 128, 121, -1,
	122, -1, 119, -1, 146, 140, 137, -1, 138, 156, 110, 107, -1, 108, 101, -1,
	102, -1, 99, -1, 126, 120, 117, -1, 118, 136, 106, 100, 97, -1, 98, 116, 96,
	-1, -2,
}

var tmLalr = []int32{
	8, -1, 9, -1, 10, -1, 0, 211, 2, 211, 3, 211, 4, 211, 5, 211, 6, 211, 7, 211,
	11, 211, -1, -2, 8, -1, 9, -1, 10, -1, 0, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7,
	2, 11, 2, 12, 2, 14, 2, 16, 2, 17, 2, 18, 2, 19, 2, 21, 2, 28, 2, 29, 2, 30,
	2, -1, -2, 2, -1, 3, -1, 4, -1, 5, -1, 6, -1, 7, -1, 11, -1, 0, 213, -1, -2,
	2, -1, 3, -1, 4, -1, 5, -1, 6, -1, 7, -1, 11, -1, 0, 212, -1, -2, 8, -1, 9,
	-1, 10, -1, 0, 208, 2, 208, 3, 208, 4, 208, 5, 208, 6, 208, 7, 208, 11, 208,
	-1, -2, 8, -1, 9, -1, 10, -1, 11, 67, 12, 67, 29, 67, -1, -2, 8, -1, 9, -1,
	10, -1, 11, 92, 12, 92, 29, 92, -1, -2, 8, -1, 9, -1, 10, -1, 12, 189, 29,
	189, -1, -2, 8, -1, 9, -1, 10, -1, 11, 67, 12, 67, 29, 67, -1, -2, 8, -1, 9,
	-1, 10, -1, 11, 92, 12, 92, 29, 92, -1, -2, 8, -1, 9, -1, 10, -1, 17, 176,
	29, 176, -1, -2, 8, -1, 9, -1, 10, -1, 11, 63, 12, 63, 29, 63, -1, -2, 8, -1,
	9, -1, 10, -1, 11, 84, 12, 84, 29, 84, -1, -2, 13, -1, 8, 48, 9, 48, 10, 48,
	21, 48, -1, -2, 13, -1, 8, 50, 9, 50, 10, 50, 21, 50, -1, -2, 13, -1, 8, 52,
	9, 52, 10, 52, 21, 52, -1, -2, 27, -1, 8, 22, 15, 22, -1, -2, 27, -1, 8, 22,
	29, 22, -1, -2, 15, 38, 16, 41, -1, -2,
}

var tmGoto = []int32{
	0, 2, 2, 6, 10, 14, 18, 22, 26, 232, 426, 620, 640, 790, 796, 806, 812, 856,
	872, 876, 892, 894, 1100, 1102, 1114, 1126, 1138, 1150, 1154, 1172, 1212,
	1306, 1500, 1692, 1884, 1898, 1910, 1922, 1934, 1946, 1956, 1960, 1962, 1964,
	1976, 1980, 1982, 1986, 1988, 1990, 1992, 1996, 2088, 2096, 2104, 2106, 2108,
	2116, 2118, 2126, 2132, 2140, 2148, 2156, 2158, 2166, 2170, 2178, 2186, 2194,
	2202, 2204, 2208, 2216, 2218, 2226, 2290, 2306, 2322, 2324, 2332, 2336, 2338,
	2354, 2370, 2386, 2390, 2398, 2400, 2402, 2406, 2410, 2414, 2418, 2420,
}

var tmFromTo = []int16{
	443, 444, 7, 11, 8, 11, 7, 12, 8, 12, 7, 13, 8, 13, 7, 14, 8, 14, 7, 15, 8,
	15, 7, 16, 8, 16, 0, 1, 6, 9, 24, 1, 27, 1, 29, 1, 31, 1, 33, 1, 41, 1, 43,
	1, 45, 1, 47, 1, 53, 1, 54, 1, 57, 1, 60, 1, 63, 1, 66, 1, 69, 1, 98, 1, 99,
	1, 107, 1, 108, 1, 113, 1, 120, 149, 121, 149, 131, 1, 139, 1, 144, 1, 169,
	1, 170, 1, 174, 1, 175, 1, 179, 1, 180, 1, 189, 1, 197, 1, 198, 1, 202, 1,
	203, 1, 204, 1, 207, 1, 209, 149, 213, 149, 219, 1, 225, 1, 228, 1, 230, 1,
	233, 1, 234, 1, 235, 1, 237, 149, 239, 149, 251, 1, 254, 1, 257, 1, 258, 1,
	260, 1, 263, 1, 265, 1, 268, 1, 275, 1, 276, 1, 278, 1, 281, 1, 285, 1, 287,
	1, 288, 1, 290, 1, 293, 1, 295, 1, 296, 1, 298, 1, 301, 1, 305, 1, 307, 1,
	308, 1, 313, 1, 316, 1, 320, 1, 322, 1, 323, 1, 325, 1, 328, 1, 332, 1, 334,
	1, 335, 1, 340, 1, 343, 1, 347, 1, 355, 1, 358, 1, 362, 1, 364, 1, 365, 1,
	370, 1, 373, 1, 377, 1, 385, 1, 396, 1, 399, 1, 403, 1, 411, 1, 427, 1, 0, 2,
	6, 2, 24, 2, 27, 2, 29, 2, 31, 2, 33, 2, 41, 2, 43, 2, 45, 2, 47, 2, 53, 2,
	54, 2, 57, 2, 60, 2, 63, 2, 66, 2, 69, 2, 98, 2, 99, 2, 107, 2, 108, 2, 113,
	2, 131, 2, 139, 2, 144, 2, 169, 2, 170, 2, 174, 2, 175, 2, 179, 2, 180, 2,
	189, 2, 197, 2, 198, 2, 202, 2, 203, 2, 204, 2, 207, 2, 219, 2, 225, 2, 228,
	2, 230, 2, 233, 2, 234, 2, 235, 2, 251, 2, 254, 2, 257, 2, 258, 2, 260, 2,
	263, 2, 265, 2, 268, 2, 275, 2, 276, 2, 278, 2, 281, 2, 285, 2, 287, 2, 288,
	2, 290, 2, 293, 2, 295, 2, 296, 2, 298, 2, 301, 2, 305, 2, 307, 2, 308, 2,
	313, 2, 316, 2, 320, 2, 322, 2, 323, 2, 325, 2, 328, 2, 332, 2, 334, 2, 335,
	2, 340, 2, 343, 2, 347, 2, 355, 2, 358, 2, 362, 2, 364, 2, 365, 2, 370, 2,
	373, 2, 377, 2, 385, 2, 396, 2, 399, 2, 403, 2, 411, 2, 427, 2, 0, 3, 6, 3,
	24, 3, 27, 3, 29, 3, 31, 3, 33, 3, 41, 3, 43, 3, 45, 3, 47, 3, 53, 3, 54, 3,
	57, 3, 60, 3, 63, 3, 66, 3, 69, 3, 98, 3, 99, 3, 107, 3, 108, 3, 113, 3, 131,
	3, 139, 3, 144, 3, 169, 3, 170, 3, 174, 3, 175, 3, 179, 3, 180, 3, 189, 3,
	197, 3, 198, 3, 202, 3, 203, 3, 204, 3, 207, 3, 219, 3, 225, 3, 228, 3, 230,
	3, 233, 3, 234, 3, 235, 3, 251, 3, 254, 3, 257, 3, 258, 3, 260, 3, 263, 3,
	265, 3, 268, 3, 275, 3, 276, 3, 278, 3, 281, 3, 285, 3, 287, 3, 288, 3, 290,
	3, 293, 3, 295, 3, 296, 3, 298, 3, 301, 3, 305, 3, 307, 3, 308, 3, 313, 3,
	316, 3, 320, 3, 322, 3, 323, 3, 325, 3, 328, 3, 332, 3, 334, 3, 335, 3, 340,
	3, 343, 3, 347, 3, 355, 3, 358, 3, 362, 3, 364, 3, 365, 3, 370, 3, 373, 3,
	377, 3, 385, 3, 396, 3, 399, 3, 403, 3, 411, 3, 427, 3, 7, 17, 8, 17, 59, 95,
	62, 104, 94, 95, 102, 95, 103, 104, 111, 104, 134, 95, 142, 104, 11, 26, 12,
	28, 13, 30, 14, 32, 15, 34, 16, 36, 41, 51, 49, 34, 52, 51, 56, 51, 57, 51,
	59, 96, 62, 105, 64, 112, 86, 51, 92, 51, 93, 51, 94, 96, 102, 96, 103, 105,
	111, 105, 120, 34, 121, 34, 126, 51, 131, 161, 134, 96, 139, 161, 142, 105,
	144, 161, 162, 161, 164, 161, 170, 161, 172, 161, 175, 161, 177, 161, 180,
	161, 183, 34, 196, 161, 201, 161, 206, 161, 214, 161, 230, 161, 237, 34, 239,
	34, 251, 161, 255, 161, 258, 161, 260, 161, 265, 161, 274, 161, 276, 161,
	278, 161, 284, 161, 286, 161, 288, 161, 290, 161, 294, 161, 296, 161, 298,
	161, 304, 161, 306, 161, 308, 161, 319, 161, 321, 161, 323, 161, 325, 161,
	331, 161, 333, 161, 335, 161, 346, 161, 361, 161, 363, 161, 365, 161, 376,
	161, 402, 161, 166, 190, 167, 190, 168, 190, 49, 70, 131, 162, 164, 162, 170,
	162, 196, 162, 188, 215, 209, 238, 242, 271, 98, 131, 107, 139, 132, 170,
	140, 175, 158, 183, 187, 214, 204, 230, 228, 251, 232, 258, 233, 260, 235,
	265, 253, 276, 254, 278, 262, 288, 263, 290, 267, 296, 268, 298, 280, 308,
	292, 323, 293, 325, 300, 335, 327, 365, 47, 64, 65, 64, 68, 64, 69, 64, 114,
	64, 118, 64, 119, 64, 147, 64, 113, 144, 145, 180, 179, 204, 203, 228, 205,
	233, 207, 235, 229, 254, 234, 263, 236, 268, 264, 293, 37, 50, 17, 38, 53,
	87, 83, 122, 85, 123, 88, 125, 95, 129, 104, 137, 169, 194, 174, 199, 189,
	216, 195, 218, 197, 220, 198, 222, 200, 224, 202, 226, 204, 231, 217, 243,
	219, 244, 221, 246, 223, 247, 225, 248, 227, 250, 228, 252, 232, 259, 233,
	261, 235, 266, 245, 272, 249, 273, 253, 277, 254, 279, 257, 282, 262, 289,
	263, 291, 267, 297, 268, 299, 275, 302, 280, 309, 281, 310, 283, 312, 285,
	314, 287, 317, 292, 324, 293, 326, 295, 329, 300, 336, 301, 337, 303, 339,
	305, 341, 307, 344, 311, 348, 313, 349, 315, 351, 316, 352, 318, 354, 320,
	356, 322, 359, 327, 366, 328, 367, 330, 369, 332, 371, 334, 374, 338, 378,
	340, 379, 342, 381, 343, 382, 345, 384, 347, 386, 350, 388, 353, 389, 355,
	390, 357, 392, 358, 393, 360, 395, 362, 397, 364, 400, 368, 404, 370, 405,
	372, 407, 373, 408, 375, 410, 377, 412, 380, 414, 383, 415, 385, 416, 387,
	418, 391, 419, 394, 420, 396, 421, 398, 423, 399, 424, 401, 426, 403, 428,
	406, 430, 409, 431, 411, 432, 413, 434, 417, 435, 422, 436, 425, 437, 427,
	438, 429, 440, 433, 441, 439, 442, 35, 49, 49, 71, 120, 71, 121, 71, 183, 71,
	237, 71, 239, 71, 49, 72, 120, 72, 121, 72, 183, 72, 237, 72, 239, 72, 49,
	73, 120, 73, 121, 73, 183, 73, 237, 73, 239, 73, 49, 74, 120, 74, 121, 74,
	183, 74, 237, 74, 239, 74, 182, 208, 184, 212, 27, 41, 29, 43, 31, 45, 33,
	47, 42, 57, 44, 60, 46, 63, 48, 69, 49, 75, 17, 39, 56, 90, 59, 97, 62, 106,
	68, 116, 86, 124, 93, 127, 94, 128, 95, 130, 102, 135, 103, 136, 104, 138,
	111, 143, 114, 146, 119, 148, 126, 160, 134, 171, 142, 176, 147, 181, 213,
	240, 50, 84, 131, 163, 139, 163, 144, 163, 162, 185, 164, 163, 170, 163, 172,
	163, 175, 163, 177, 163, 180, 163, 196, 163, 201, 163, 206, 163, 214, 163,
	230, 163, 251, 163, 255, 163, 258, 163, 260, 163, 265, 163, 274, 163, 276,
	163, 278, 163, 284, 163, 286, 163, 288, 163, 290, 163, 294, 163, 296, 163,
	298, 163, 304, 163, 306, 163, 308, 163, 319, 163, 321, 163, 323, 163, 325,
	163, 331, 163, 333, 163, 335, 163, 346, 163, 361, 163, 363, 163, 365, 163,
	376, 163, 402, 163, 0, 4, 6, 10, 24, 4, 27, 4, 29, 4, 31, 4, 33, 4, 41, 4,
	43, 4, 45, 4, 47, 4, 53, 4, 54, 4, 57, 4, 60, 4, 63, 4, 66, 4, 69, 4, 98, 4,
	99, 4, 107, 4, 108, 4, 113, 4, 131, 4, 139, 4, 144, 4, 169, 4, 170, 4, 174,
	4, 175, 4, 179, 4, 180, 4, 189, 4, 197, 4, 198, 4, 202, 4, 203, 4, 204, 4,
	207, 4, 219, 4, 225, 4, 228, 4, 230, 4, 233, 4, 234, 4, 235, 4, 251, 4, 254,
	4, 257, 4, 258, 4, 260, 4, 263, 4, 265, 4, 268, 4, 275, 4, 276, 4, 278, 4,
	281, 4, 285, 4, 287, 4, 288, 4, 290, 4, 293, 4, 295, 4, 296, 4, 298, 4, 301,
	4, 305, 4, 307, 4, 308, 4, 313, 4, 316, 4, 320, 4, 322, 4, 323, 4, 325, 4,
	328, 4, 332, 4, 334, 4, 335, 4, 340, 4, 343, 4, 347, 4, 355, 4, 358, 4, 362,
	4, 364, 4, 365, 4, 370, 4, 373, 4, 377, 4, 385, 4, 396, 4, 399, 4, 403, 4,
	411, 4, 427, 4, 0, 5, 24, 40, 27, 42, 29, 44, 31, 46, 33, 48, 41, 52, 43, 58,
	45, 61, 47, 65, 53, 88, 54, 89, 57, 92, 60, 101, 63, 110, 66, 115, 69, 118,
	98, 132, 99, 133, 107, 140, 108, 141, 113, 145, 131, 164, 139, 172, 144, 177,
	169, 195, 170, 196, 174, 200, 175, 201, 179, 205, 180, 206, 189, 217, 197,
	221, 198, 223, 202, 227, 203, 229, 204, 232, 207, 236, 219, 245, 225, 249,
	228, 253, 230, 255, 233, 262, 234, 264, 235, 267, 251, 274, 254, 280, 257,
	283, 258, 284, 260, 286, 263, 292, 265, 294, 268, 300, 275, 303, 276, 304,
	278, 306, 281, 311, 285, 315, 287, 318, 288, 319, 290, 321, 293, 327, 295,
	330, 296, 331, 298, 333, 301, 338, 305, 342, 307, 345, 308, 346, 313, 350,
	316, 353, 320, 357, 322, 360, 323, 361, 325, 363, 328, 368, 332, 372, 334,
	375, 335, 376, 340, 380, 343, 383, 347, 387, 355, 391, 358, 394, 362, 398,
	364, 401, 365, 402, 370, 406, 373, 409, 377, 413, 385, 417, 396, 422, 399,
	425, 403, 429, 411, 433, 427, 439, 0, 6, 24, 6, 27, 6, 29, 6, 31, 6, 33, 6,
	41, 6, 43, 6, 45, 6, 47, 6, 53, 6, 54, 6, 57, 6, 60, 6, 63, 6, 66, 6, 69, 6,
	98, 6, 99, 6, 107, 6, 108, 6, 113, 6, 131, 6, 139, 6, 144, 6, 169, 6, 170, 6,
	174, 6, 175, 6, 179, 6, 180, 6, 189, 6, 197, 6, 198, 6, 202, 6, 203, 6, 204,
	6, 207, 6, 219, 6, 225, 6, 228, 6, 230, 6, 233, 6, 234, 6, 235, 6, 251, 6,
	254, 6, 257, 6, 258, 6, 260, 6, 263, 6, 265, 6, 268, 6, 275, 6, 276, 6, 278,
	6, 281, 6, 285, 6, 287, 6, 288, 6, 290, 6, 293, 6, 295, 6, 296, 6, 298, 6,
	301, 6, 305, 6, 307, 6, 308, 6, 313, 6, 316, 6, 320, 6, 322, 6, 323, 6, 325,
	6, 328, 6, 332, 6, 334, 6, 335, 6, 340, 6, 343, 6, 347, 6, 355, 6, 358, 6,
	362, 6, 364, 6, 365, 6, 370, 6, 373, 6, 377, 6, 385, 6, 396, 6, 399, 6, 403,
	6, 411, 6, 427, 6, 15, 35, 49, 76, 120, 150, 121, 150, 183, 150, 237, 150,
	239, 150, 49, 77, 120, 151, 121, 151, 183, 151, 237, 151, 239, 151, 49, 78,
	120, 152, 121, 152, 183, 152, 237, 152, 239, 152, 49, 79, 120, 153, 121, 153,
	183, 153, 237, 153, 239, 153, 49, 80, 120, 154, 121, 154, 183, 154, 237, 154,
	239, 154, 120, 155, 121, 157, 183, 210, 237, 155, 239, 157, 120, 156, 237,
	269, 49, 81, 156, 182, 70, 120, 75, 121, 182, 209, 184, 213, 208, 237, 212,
	239, 121, 158, 239, 158, 183, 211, 121, 159, 239, 270, 49, 82, 159, 184, 49,
	83, 7, 18, 8, 18, 131, 165, 139, 173, 144, 178, 162, 186, 164, 165, 170, 165,
	172, 173, 175, 173, 177, 178, 180, 178, 196, 165, 201, 173, 206, 178, 214,
	241, 230, 256, 251, 256, 255, 256, 258, 256, 260, 256, 265, 256, 274, 256,
	276, 256, 278, 256, 284, 256, 286, 256, 288, 256, 290, 256, 294, 256, 296,
	256, 298, 256, 304, 256, 306, 256, 308, 256, 319, 256, 321, 256, 323, 256,
	325, 256, 331, 256, 333, 256, 335, 256, 346, 256, 361, 256, 363, 256, 365,
	256, 376, 256, 402, 256, 59, 98, 94, 98, 102, 98, 134, 98, 131, 166, 164,
	166, 170, 166, 196, 166, 162, 187, 214, 242, 131, 167, 164, 167, 170, 167,
	196, 167, 162, 188, 131, 168, 164, 168, 170, 168, 196, 168, 166, 191, 167,
	192, 168, 193, 131, 169, 164, 189, 170, 197, 196, 219, 59, 99, 94, 99, 102,
	99, 134, 99, 59, 100, 94, 100, 102, 100, 134, 100, 12, 29, 43, 59, 58, 94,
	60, 102, 101, 134, 7, 19, 8, 19, 62, 107, 103, 107, 111, 107, 142, 107, 139,
	174, 172, 198, 175, 202, 201, 225, 62, 108, 103, 108, 111, 108, 142, 108, 62,
	109, 103, 109, 111, 109, 142, 109, 13, 31, 7, 20, 8, 20, 45, 62, 61, 103, 63,
	111, 110, 142, 64, 113, 144, 179, 177, 203, 180, 207, 206, 234, 230, 257,
	251, 275, 255, 281, 258, 285, 260, 287, 265, 295, 274, 301, 276, 305, 278,
	307, 284, 313, 286, 316, 288, 320, 290, 322, 294, 328, 296, 332, 298, 334,
	304, 340, 306, 343, 308, 347, 319, 355, 321, 358, 323, 362, 325, 364, 331,
	370, 333, 373, 335, 377, 346, 385, 361, 396, 363, 399, 365, 403, 376, 411,
	402, 427, 47, 66, 65, 66, 68, 66, 69, 66, 114, 66, 118, 66, 119, 66, 147, 66,
	47, 67, 65, 67, 68, 117, 69, 67, 114, 117, 118, 67, 119, 117, 147, 117, 14,
	33, 47, 68, 65, 114, 69, 119, 118, 147, 7, 21, 8, 21, 11, 27, 41, 53, 52, 53,
	56, 53, 57, 53, 86, 53, 92, 53, 93, 53, 126, 53, 41, 54, 52, 54, 56, 54, 57,
	54, 86, 54, 92, 54, 93, 54, 126, 54, 41, 55, 52, 55, 56, 91, 57, 55, 86, 91,
	92, 55, 93, 91, 126, 91, 7, 22, 8, 22, 41, 56, 52, 86, 57, 93, 92, 126, 16,
	37, 50, 85, 7, 23, 8, 23, 7, 24, 8, 24, 7, 25, 8, 25, 0, 7, 5, 8, 0, 443,
}

var tmRuleLen = []int8{
	1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 4, 0, 2, 0, 1, 1, 3,
	6, 4, 0, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 3, 1, 2, 1, 2, 1, 2,
	1, 7, 6, 6, 5, 6, 5, 5, 4, 2, 2, 1, 2, 1, 2, 0, 7, 6, 6, 5, 1, 1, 7, 6, 6, 5,
	6, 5, 5, 4, 2, 2, 1, 2, 1, 7, 6, 6, 5, 2, 0, 1, 1, 1, 14, 13, 13, 12, 13, 12,
	12, 11, 10, 9, 13, 12, 12, 11, 12, 11, 11, 10, 9, 8, 13, 12, 12, 11, 12, 11,
	11, 10, 9, 8, 12, 11, 11, 10, 11, 10, 10, 9, 8, 7, 13, 12, 12, 11, 12, 11,
	11, 10, 9, 8, 12, 11, 11, 10, 11, 10, 10, 9, 8, 7, 12, 11, 11, 10, 11, 10,
	10, 9, 8, 7, 11, 10, 10, 9, 10, 9, 9, 8, 7, 6, 1, 2, 1, 2, 1, 7, 6, 6, 5, 1,
	1, 3, 2, 1, 2, 7, 6, 6, 5, 2, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 0,
	2, 1,
}

var tmRuleSymbol = []int32{
	31, 31, 32, 33, 33, 33, 33, 34, 35, 36, 37, 38, 39, 39, 39, 39, 39, 40, 41,
	42, 42, 43, 43, 44, 45, 46, 47, 48, 48, 49, 49, 49, 49, 49, 49, 49, 50, 51,
	51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 60, 60, 60, 60, 60, 61, 61, 61, 61,
	61, 61, 61, 61, 61, 61, 62, 62, 63, 64, 64, 65, 65, 65, 65, 66, 67, 68, 68,
	68, 68, 68, 68, 68, 68, 68, 68, 69, 69, 70, 71, 71, 71, 71, 72, 72, 73, 74,
	75, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
	76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
	76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
	76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
	76, 76, 76, 76, 76, 77, 77, 78, 79, 79, 80, 80, 80, 80, 81, 82, 83, 83, 84,
	84, 85, 85, 85, 85, 86, 86, 87, 88, 89, 90, 90, 90, 90, 90, 90, 90, 90, 91,
	91, 92, 92, 93, 93,
}

var tmRuleType = [...]NodeType{
	0,            // Comment : BlockComment
	0,            // Comment : EolComment
	0,            // WhiteSpace : WhiteSpace$1
	0,            // WhiteSpace$1 : WhiteSpace$1 Comment
	0,            // WhiteSpace$1 : WhiteSpace$1 WS
	0,            // WhiteSpace$1 : Comment
	0,            // WhiteSpace$1 : WS
	OptionName,   // OptionName : Name
	OptionString, // OptionString : StringLiteral
	OptionBool,   // OptionBool : BoolLiteral
	OptionInt,    // OptionInt : IntLiteral
	OptionFloat,  // OptionFloat : FloatLiteral
	0,            // OptionScalar : OptionName
	0,            // OptionScalar : OptionString
	0,            // OptionScalar : OptionBool
	0,            // OptionScalar : OptionInt
	0,            // OptionScalar : OptionFloat
	0,            // OptionSliceElement : OptionScalar
	OptionSlice,  // OptionSlice : '[' Ws_optlist OptionSliceElement OptionSlice$1 Ws_optlist ']'
	0,            // OptionSlice$1 : OptionSlice$1 ',' Ws_optlist OptionSliceElement
	0,            // OptionSlice$1 :
	0,            // Ws_optlist : Ws_optlist WS
	0,            // Ws_optlist :
	0,            // OptionMapKey : OptionScalar
	0,            // OptionMapValue : OptionScalar
	0,            // OptionMapEntry : OptionMapKey ':' OptionMapValue
	OptionMap,    // OptionMap : '{' Ws_optlist OptionMapEntry OptionMap$1 Ws_optlist '}'
	0,            // OptionMap$1 : OptionMap$1 ',' Ws_optlist OptionMapEntry
	0,            // OptionMap$1 :
	0,            // OptionValue : OptionName
	0,            // OptionValue : OptionString
	0,            // OptionValue : OptionBool
	0,            // OptionValue : OptionInt
	0,            // OptionValue : OptionFloat
	0,            // OptionValue : OptionSlice
	0,            // OptionValue : OptionMap
	0,            // Option : 'option' OptionName '=' OptionValue ';'
	0,            // TypeRef : Name
	0,            // TypeRef : Primitive
	FieldName,    // FieldName : Name
	ScalarType,   // ScalarType : TypeRef
	MapKeyType,   // MapKeyType : Primitive
	MapValueType, // MapValueType : TypeRef
	0,            // MapType : '[' MapKeyType ':' MapValueType ']'
	ListElement,  // ListElementType : TypeRef
	0,            // ListType : '[' ListElementType ']'
	FieldMod,     // FieldMod : Modifier
	0,            // FieldType : ScalarType FieldMod
	0,            // FieldType : ScalarType
	0,            // FieldType : MapType FieldMod
	0,            // FieldType : MapType
	0,            // FieldType : ListType FieldMod
	0,            // FieldType : ListType
	0,            // FieldDef : FieldName WhiteSpace ':' WhiteSpace FieldType WhiteSpace ';'
	0,            // FieldDef : FieldName WhiteSpace ':' WhiteSpace FieldType ';'
	0,            // FieldDef : FieldName WhiteSpace ':' FieldType WhiteSpace ';'
	0,            // FieldDef : FieldName WhiteSpace ':' FieldType ';'
	0,            // FieldDef : FieldName ':' WhiteSpace FieldType WhiteSpace ';'
	0,            // FieldDef : FieldName ':' WhiteSpace FieldType ';'
	0,            // FieldDef : FieldName ':' FieldType WhiteSpace ';'
	0,            // FieldDef : FieldName ':' FieldType ';'
	0,            // FieldDef : error ';'
	0,            // FieldDef : error '}'
	0,            // FieldDefList : FieldDef
	0,            // FieldDefList : FieldDef WhiteSpace
	MessageName,  // MessageName : Name
	0,            // FieldDefList_optlist : FieldDefList_optlist FieldDefList
	0,            // FieldDefList_optlist :
	0,            // Message : 'message' MessageName WhiteSpace '{' WhiteSpace FieldDefList_optlist '}'
	0,            // Message : 'message' MessageName WhiteSpace '{' FieldDefList_optlist '}'
	0,            // Message : 'message' MessageName '{' WhiteSpace FieldDefList_optlist '}'
	0,            // Message : 'message' MessageName '{' FieldDefList_optlist '}'
	FieldName,    // UnionMemberName : Name
	ScalarType,   // UnionMemberType : TypeRef
	0,            // UnionMember : UnionMemberName WhiteSpace ':' WhiteSpace UnionMemberType WhiteSpace ';'
	0,            // UnionMember : UnionMemberName WhiteSpace ':' WhiteSpace UnionMemberType ';'
	0,            // UnionMember : UnionMemberName WhiteSpace ':' UnionMemberType WhiteSpace ';'
	0,            // UnionMember : UnionMemberName WhiteSpace ':' UnionMemberType ';'
	0,            // UnionMember : UnionMemberName ':' WhiteSpace UnionMemberType WhiteSpace ';'
	0,            // UnionMember : UnionMemberName ':' WhiteSpace UnionMemberType ';'
	0,            // UnionMember : UnionMemberName ':' UnionMemberType WhiteSpace ';'
	0,            // UnionMember : UnionMemberName ':' UnionMemberType ';'
	0,            // UnionMember : error ';'
	0,            // UnionMember : error '}'
	0,            // UnionMemberList : UnionMember
	0,            // UnionMemberList : UnionMember WhiteSpace
	UnionName,    // UnionName : Name
	0,            // Union : 'union' UnionName WhiteSpace '{' WhiteSpace UnionMemberList_optlist '}'
	0,            // Union : 'union' UnionName WhiteSpace '{' UnionMemberList_optlist '}'
	0,            // Union : 'union' UnionName '{' WhiteSpace UnionMemberList_optlist '}'
	0,            // Union : 'union' UnionName '{' UnionMemberList_optlist '}'
	0,            // UnionMemberList_optlist : UnionMemberList_optlist UnionMemberList
	0,            // UnionMemberList_optlist :
	RpcName,      // RpcName : Name
	RpcRequest,   // RpcRequest : TypeRef
	RpcResponse,  // RpcResponse : TypeRef
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest WhiteSpace ')' ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' WhiteSpace RpcRequest ')' ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest WhiteSpace ')' ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName WhiteSpace '(' RpcRequest ')' ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest WhiteSpace ')' ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' WhiteSpace RpcRequest ')' ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest WhiteSpace ')' ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' WhiteSpace ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' WhiteSpace ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' WhiteSpace ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' ':' WhiteSpace RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' ':' WhiteSpace RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' ':' RpcResponse WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' ':' RpcResponse ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' WhiteSpace ';'
	0,            // Method : 'rpc' RpcName '(' RpcRequest ')' ';'
	0,            // MethodList : Method
	0,            // MethodList : Method WhiteSpace
	ServiceName,  // ServiceName : Name
	0,            // MethodList_list : MethodList_list MethodList
	0,            // MethodList_list : MethodList
	0,            // Service : 'service' ServiceName WhiteSpace '{' WhiteSpace MethodList_list '}'
	0,            // Service : 'service' ServiceName WhiteSpace '{' MethodList_list '}'
	0,            // Service : 'service' ServiceName '{' WhiteSpace MethodList_list '}'
	0,            // Service : 'service' ServiceName '{' MethodList_list '}'
	EnumName,     // EnumName : Name
	EnumValue,    // EnumValue : Name
	0,            // EnumField : EnumValue WhiteSpace ';'
	0,            // EnumField : EnumValue ';'
	0,            // EnumValueList : EnumField
	0,            // EnumValueList : EnumField WhiteSpace
	0,            // Enum : 'enum' EnumName WhiteSpace '{' WhiteSpace EnumValueList_list '}'
	0,            // Enum : 'enum' EnumName WhiteSpace '{' EnumValueList_list '}'
	0,            // Enum : 'enum' EnumName '{' WhiteSpace EnumValueList_list '}'
	0,            // Enum : 'enum' EnumName '{' EnumValueList_list '}'
	0,            // EnumValueList_list : EnumValueList_list EnumValueList
	0,            // EnumValueList_list : EnumValueList
	AliasName,    // AliasName : Name
	AliasType,    // AliasType : Primitive
	0,            // Alias : 'alias' AliasName '->' AliasType ';'
	0,            // Definition : Message
	0,            // Definition : Union
	0,            // Definition : Service
	0,            // Definition : Enum
	0,            // Definition : Option
	0,            // Definition : Alias
	0,            // Definition : error ';'
	0,            // Definition : error '}'
	0,            // DefinitionList : Definition
	0,            // DefinitionList : Definition WhiteSpace
	0,            // DefinitionList_optlist : DefinitionList_optlist DefinitionList
	0,            // DefinitionList_optlist :
	0,            // ServoFile : WhiteSpace DefinitionList_optlist
	0,            // ServoFile : DefinitionList_optlist
}

// set(follow ERROR) = SEMICOLON, RBRACE
var afterErr = []token.Type{
	21, 29,
}
