package generate

import (
	"github.com/dave/jennifer/jen"
	"github.com/egoodhall/servo/cmd/servoc-ext_gohttp/options"
	"github.com/egoodhall/servo/pkg/ast"
)

const (
	pkgEcho     = "github.com/labstack/echo/v4"
	pkgHttp     = "net/http"
	pkgHttptest = "net/http/httptest"
	pkgUrl      = "net/url"
	pkgContext  = "context"
	pkgBytes    = "bytes"
	pkgJson     = "encoding/json"
	pkgErrors   = "errors"
	pkgStrconv  = "strconv"
)

func ServicesAndClients(file *ast.File, options options.Options) (*jen.File, error) {
	gofile := jen.NewFile(options.Package)
	gofile.PackageComment("Code generated by servoc (gohttp plugin). DO NOT EDIT.")

	gofile.ImportNames(map[string]string{
		pkgContext: "context",
		pkgEcho:    "echo",
		pkgHttp:    "http",
		pkgUrl:     "url",
		pkgBytes:   "bytes",
		pkgJson:    "json",
		pkgErrors:  "errors",
	})

	for _, svc := range file.Services {
		Server(gofile, svc)
		Client(gofile, svc)
		TestClient(gofile, svc)
	}

	return gofile, nil
}
